### ISSUE TITLE
go: unknown relocation type 42; compiled without -fpic?

### ISSUE THREAD

**Issue by xu-cheng** [Linuxbrew/linuxbrew#1057]
_From @int03h on April 8, 2016 15:16_

Trying to brew install go on debian SID .. (I did try it on testing too) .. it does compile natively on the OS, not problem. ( tried with and without export `HOMEBREW_BUILD_FROM_SOURCE=1`) 

I compiled ethereum-cpp successfully but I can't get GETH ( go version to compile because of it's dependency on golang ) 
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

https://gist.github.com/1b3367f01fd05e67af2c027782cab3f9

```
/tmp/go20160408-29305-1dninkg/go/gobootstrap/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
/tmp/go20160408-29305-1dninkg/go/gobootstrap/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
runtime/cgo(.text): unexpected relocation type 298
runtime/cgo(.text): unexpected relocation type 298
# cmd/go
/tmp/go20160408-29305-1dninkg/go/gobootstrap/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
/tmp/go20160408-29305-1dninkg/go/gobootstrap/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
runtime/cgo(.text): unexpected relocation type 298
runtime/cgo(.text): unexpected relocation type 298
```

thanks! 
int

_Copied from original issue: Homebrew/brew#48_

**Comment by sjackman** [comment]
I have seen other issues with this error message reported. Try
`brew install binutils go`
I'm not convinced that will work, but it's worth a shot.

**Comment by sjackman** [comment]
It looks as though this issue is known upstream. See
https://github.com/golang/go/issues/13114
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807136

**Comment by sjackman** [comment]
Maybe my `binutils` guess is correct. See https://github.com/Linuxbrew/linuxbrew/issues/1057

> Your system linker (/usr/bin/ld) is not up to date with your compiler/assembler. It's not a Go problem at all.

Please report `/usr/bin/ld --version`

**Comment by int03h** [comment]
HI thanks for all the help! :) 

I did see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807136 but I assumed that it would be "handled" by brew since it's installed in the native environment - i.e. it is buildable (somehow)

doing a dpkg -l : 
ii  go                                     1.6-godeb1                   amd64        Go language compiler and tools (gc)
 
testing : 
**brew reinstall binutils go**
==> Reinstalling binutils
==> Downloading http://ftpmirror.gnu.org/binutils/binutils-2.26.tar.gz
Already downloaded: /root/.cache/Homebrew/binutils-2.26.tar.gz
==> ./configure  --with-sysroot=/ --prefix=/root/.linuxbrew/Cellar/binutils/2.26
==> make
==> make install
/root/.linuxbrew/Cellar/binutils/2.26: 3,178 files, 192.2M, built in 1 minute 50 seconds
==> Reinstalling go
==> Downloading https://storage.googleapis.com/golang/go1.6.src.tar.gz
Already downloaded: /root/.cache/Homebrew/go-1.6.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
Already downloaded: /root/.cache/Homebrew/go--gobootstrap-64.tar.gz
==> ./make.bash --no-clean
Last 15 lines from /root/.cache/Homebrew/Logs/go/01.make.bash:
net/http/pprof
cmd/pprof
net/rpc
net/http/fcgi
net/rpc/jsonrpc
# cmd/pprof
/tmp/go20160408-30952-xu75d5/go/gobootstrap/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
/tmp/go20160408-30952-xu75d5/go/gobootstrap/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
runtime/cgo(.text): unexpected relocation type 298
runtime/cgo(.text): unexpected relocation type 298
# cmd/go
/tmp/go20160408-30952-xu75d5/go/gobootstrap/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
/tmp/go20160408-30952-xu75d5/go/gobootstrap/pkg/linux_amd64/runtime/cgo.a(_all.o): unknown relocation type 42; compiled without -fpic?
runtime/cgo(.text): unexpected relocation type 298
runtime/cgo(.text): unexpected relocation type 298

i.e. it throws the same errors.

**root@crunk:/# /usr/bin/ld --version **
GNU ld (GNU Binutils for Debian) 2.26

**and root@crunk:/# /root/.linuxbrew/bin/ld -v**
GNU ld (GNU Binutils) 2.26.20160125

Thanks!

**Comment by sjackman** [comment]
This comment https://github.com/golang/go/issues/13114#issuecomment-186922245 mentions setting the environment variable `CGO_ENABLED=0`, but I believe that has to be done when compiling go `1.4`, and we download a binary of `go 1.4`, used to bootstrap `go 1.5`.

**Comment by sjackman** [comment]
Perhaps I misunderstood though. Try
```sh
CGO_ENABLED=0 brew install go
```

**Comment by int03h** [comment]
Fixed ! 

root@crunk:~# CGO_ENABLED=0 brew install go
==> Downloading https://storage.googleapis.com/golang/go1.6.src.tar.gz
Already downloaded: /root/.cache/Homebrew/go-1.6.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
Already downloaded: /root/.cache/Homebrew/go--gobootstrap-64.tar.gz
==> ./make.bash --no-clean
==> ./make.bash --no-clean
==> /root/.linuxbrew/Cellar/go/1.6/bin/go install -race std
==> Cloning https://go.googlesource.com/tools.git
Cloning into '/root/.cache/Homebrew/go--gotools--git'...
remote: Sending approximately 10.68 MiB ...
remote: Counting objects: 774, done
remote: Finding sources: 100% (5/5)
remote: Total 15898 (delta 10660), reused 15896 (delta 10660)
Receiving objects: 100% (15898/15898), 10.28 MiB | 8.95 MiB/s, done.
Resolving deltas: 100% (10660/10660), done.
Checking connectivity... done.
==> Checking out branch release-branch.go1.6
==> go build
==> go build
==> Caveats
As of go 1.2, a valid GOPATH is required to use the `go get` command:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/root/.linuxbrew/opt/go/libexec/bin

after setting PATH and logout .. 

root@crunk:~# which go
/root/.linuxbrew/bin/go
root@crunk:~# go version
go version go1.6 linux/amd64
 
Thanks!

**Comment by sjackman** [comment]
Great!
