### ISSUE TITLE
Brew commands not found after install 

### ISSUE THREAD

**Issue by gameslayer** [Linuxbrew/linuxbrew#1102]
After successfully installing brew I try and install something via brew and got this error message

 No command 'brew' found, did you mean:
 Command 'brec' from package 'bplay' (universe)
 Command 'qbrew' from package 'qbrew' (universe)
brew: command not found

**Comment by rwhogg** [comment]
Hey @gameslayer, can you try the following please?

1. `export PATH=$HOME/.linuxbrew/bin:$PATH`
2. `hash -r` (if you're using Bash) or `rehash` (if you're using Zsh)
3. Try to run the command again?

@sjackman, maybe we should put instructions of this sort into either the output of the installer or somewhere prominent on the README, since this sort of issue seems to come up fairly frequently.

**Comment by gameslayer** [comment]
Ahh thanks so much, I thought you only had to do that if you did it the second way through git :)

**Comment by rwhogg** [comment]
No problem! Mind if I close this issue?

**Comment by gameslayer** [comment]
Yeah sure issues solved

**Comment by sjackman** [comment]
> @sjackman, maybe we should put instructions of this sort into either the output of the installer or somewhere prominent on the README, since this sort of issue seems to come up fairly frequently.

Yes, absolutely. Those instructions are already here: http://linuxbrew.sh/#installation
They should also be added to the end of the installation script. A PR would be most welcome.
