### ISSUE TITLE
"Another active Homebrew process is already using zlib."

### ISSUE THREAD

**Issue by stanley-cheung** [Linuxbrew/linuxbrew#483]
On a fresh debian wheezy VM, trying to install anything from the homebrew/php tap seems to give this "Another active Homebrew process is already using zlib." error. I have no other terminal running brew at the same time. I had raised an issue with [homebrew-php](https://github.com/Homebrew/homebrew-php/issues/1903) and they think it's a linuxbrew issue. This works fine on Mac OS X.

```
stanleycheung@stanleycheung-test:~$ brew doctor
Your system is ready to brew.
stanleycheung@stanleycheung-test:~$ brew update
Already up-to-date.
stanleycheung@stanleycheung-test:~$ brew tap homebrew/php
==> Tapping homebrew/php
Cloning into '/home/stanleycheung/.linuxbrew/Library/Taps/homebrew/homebrew-php'...
remote: Counting objects: 500, done.
remote: Compressing objects: 100% (202/202), done.
remote: Total 500 (delta 380), reused 343 (delta 297), pack-reused 0
Receiving objects: 100% (500/500), 137.58 KiB, done.
Resolving deltas: 100% (380/380), done.
Tapped 484 formulae (516 files, 2.5M)
stanleycheung@stanleycheung-test:~$ brew install php55-protobuf
==> Installing php55-protobuf from homebrew/homebrew-php
==> Tapping homebrew/dupes
Cloning into '/home/stanleycheung/.linuxbrew/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 40, done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 40 (delta 1), reused 10 (delta 0), pack-reused 0
Unpacking objects: 100% (40/40), done.
Tapped 37 formulae (98 files, 620K)
Error: Operation already in progress for zlib
Another active Homebrew process is already using zlib.
Please wait for it to finish or terminate it to continue.
```

**Comment by sjackman** [comment]
Try changing `homebrew/dupes/zlib` to `zlib` in `Abstract/abstract-php.rb` line 38.
https://github.com/Homebrew/homebrew-php/blob/970daa00d5994c5d1bdc8ff5aa547cda6f2d702f/Abstract/abstract-php.rb#L38

**Comment by sjackman** [comment]
A workaround might be `brew install zlib php55-protobuf`

**Comment by stanley-cheung** [comment]
The latter suggestion did not work, but the former did work. Asking homebrew-php whether they will consider changing `homebrew/dupes/zlib` to `zlib` in `Abstract/abstract-php.rb` in that line 38

**Comment by ablyler** [comment]
@sjackman is it possible to add absolute formula pathing support to linuxbrew?  I just did a quick search and there are a lot of packages in the homebrew core that also have this type of pathing.

**Comment by sjackman** [comment]
This issue is specific to `homebrew/dupes/zlib` and is not a more general issue. The problem is that `zlib` also exists in `homebrew/linuxbrew/zlib` to solve a cyclic dependency issue with `git`, which is needed for tapping `homebrew/dupes`. The best solution, for Linuxbrew anyway, would be to move `homebrew/dupes/zlib` to `homebrew/homebrew/zlib`.
@Homebrew/owners What do you say? Can we move `zlib`?

**Comment by tdsmith** [comment]
Would having Linuxbrew's git formula vendor zlib be a solution?

**Comment by sjackman** [comment]
Yes. I'm not generally a fan of vendoring dependencies. I think it's a hack solution and doesn't scale. I'd prefer to move zlib. Thanks for the suggestion though. I'll keep it in mind as a potential solution. (to clarify, it's `openssl` that has the cyclic dependency on `zlib`).

**Comment by DomT4** [comment]
Just FWIW, you can actually disable that `zlib` link in OpenSSL.

I've considered doing so quite a few times because compression can and has led to various security problems of not insignificant note such as the CRIME attack, Apple also tear out the default compression block with a [patch](https://opensource.apple.com/source/OpenSSL098/OpenSSL098-52/patches/12370202-CRIME.patch) in their OpenSSL, and Debian/Ubuntu/Fedora/etc have been passing `no-zlib` to `configure` for years.

The likelihood is that you'd need to force a rebuild of everything to be certain it doesn't break anything, which is why I haven't moved on it yet.

**Comment by sjackman** [comment]
Cool! Good to know. Thanks for the tip. I may do just that. Linuxbrew doesn't have (many) bottles, so the rebuild shouldn't be necessary, should it? Would users' installed formula have to be rebuilt?

**Comment by felixbuenemann** [comment]
@DomT4 CRIME can only be used against certain protocols that echo back information injected through a client, so ssl compression is still useful for many protocols like SSH, SMTP or Postgres replication. The better solution is IMHO to disable ssl compression in http servers and clients by default, then to deactivate it for all ssl apps.

**Comment by DomT4** [comment]
CRIME hasn't been the only compression attack. Compression is always useful, especially for less capable hardware, but it is an attack vector of which OpenSSL already has plenty. Neither Debian/Ubuntu enable `zlib` at compile time or dynamically.

I'm fairly sure Homebrew has only left it because it was added with the formula in 2009 and nobody has really bothered to look at it since, because OpenSSL compression isn't the most thrilling debate in the world. In an ideal world, it would just go away.

It's just something I haven't really wanted to dedicate a huge amount of energy into arguing with people about, so it keeps surviving until some terrible new vulnerability is discovered and everyone rushes to kill it off.

**Comment by sjackman** [comment]
@DomT4 Have you asked `Homebrew/homebew` whether `zlib` should be disabled in `openssl`?

**Comment by DomT4** [comment]
OpenSSL stuff tends to get referred back to me a fair bit, but if anyone else wants to comment, CC @Homebrew/owners @dunn.

It's not really on my immediate agenda, to be honest - Compression poses a threat in certain situations, but as we see all too often with OpenSSL in particular, outside of certain Linux distros people habitually favour the added functionality, even though that functionality can pose risks.

To some extent, package managers and distros have to take initiative on protecting their users. If people want a more vulnerable package they should be compiling it themselves, but winning that argument has never been easy or fun.

SSLv3's death is my next significantly change, in line with Debian stable's removal of it several months ago now. That will probably be the last API break planned until at least 2016.

**Comment by DomT4** [comment]
As an alternative though, if it saves you problems, you could vendor `zlib` into `libexec` and instead of dynamically linking against it actually compile OpenSSL against it manually. That would halt the immediate need for a cross-tap dependency on OpenSSL, and although revisioning OpenSSL may be prudent you wouldn't need to revision any of the dependencies.
