### ISSUE TITLE
cmake: formula not installing?

### ISSUE THREAD

**Issue by DomT4** [Linuxbrew/linuxbrew#562]
_From @MarcGodard on September 19, 2015 17:55_

Just installed brew on a brand-new Ubuntu virtualbox, ran doctor and update everything seemed good.

Running:
```
brew install pdf2htmlex
```

Got this error first time:
```
Error: /home/ubuntu/.linuxbrew/opt/pkg-config not present or broken
Please reinstall pkg-config. Sorry :(
```

Fixed it using:
```
ubuntu@ubuntu-VirtualBox:~$ brew reinstall pkg-config
```
Tried again...
Terminal (truncated to error):
```
ubuntu@ubuntu-VirtualBox:~$ brew install pdf2htmlex
==> Installing dependencies for pdf2htmlex: cmake, xz, libpng, freetype, fontconfig, pixman, gettext, libffi, glib, cairo, bison, flex, gobject-int
==> Installing pdf2htmlex dependency: cmake
==> Downloading http://www.cmake.org/files/v3.3/cmake-3.3.1.tar.gz
Already downloaded: /home/ubuntu/.cache/Homebrew/cmake-3.3.1.tar.gz
==> Downloading https://pypi.python.org/packages/source/s/sphinx_rtd_theme/sphinx_rtd_theme-0.1.8.tar.gz
Already downloaded: /home/ubuntu/.cache/Homebrew/cmake--sphinx_rtd_theme-0.1.8.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/cmake20150919-11014-1wujgys/cmake-3.3.1/sphinx --single-version-externally-managed 
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
cmake builds fail on CLT-only with --env=std https://github.com/Homebrew/homebrew/issues/29101
```

Getting logs as informed in troubleshooting:
```
ubuntu@ubuntu-VirtualBox:~$ brew gist-logs pdf2htmlex
Error: No logs.
```

I am unsure what to try now. Any recommendations?

_Copied from original issue: Homebrew/homebrew#44140_

**Comment by MarcGodard** [comment]
After some searching I found a solution, run the following before installing:

```
sudo apt-get install --no-install-recommends python-setuptools
```

**Comment by MarcGodard** [comment]
Ok, still can't get it installed.

Tested with brew install hello and tested it no problem.

Steps to install formula on ubuntu 14.04:

Run (because without it it breaks the pdf2html2 formula) :
```bash
sudo apt-get install --no-install-recommends python-setuptools python-dev
```

Fix a bug in a dependent formula (pico or other editor):
```bash
pico ~/.linuxbrew/Library/Formula/harfbuzz.rb
```
change ```--with-coretext=yes``` with ```--with-coretext=auto``` in the arguments list

Then run the formula:
```bash
brew install pdf2htmlex
```

If you get this common error:
```bash
Error: /home/ubuntu/.linuxbrew/opt/pkg-config not present or broken
```
run the following and try the formula again:
```bash
brew reinstall pkg-config
```

logs:
https://gist.github.com/anonymous/027ad6df5a697747cac5

error: ```configure: error: C compiler cannot create executables``` but in hello logs everything looks fine.

**Comment by mohakshah** [comment]
I was facing the same issue on Linux Mint 17.2 x64 (based off of Ubuntu 14.04). Installing python setuptools from the distribution's repo worked for me. Simply running:

`sudo apt-get install python-setuptools`

and then installing sphinx-doc from brew

`brew install spinx-doc`

works properly.

Since homebrew itself installs python setuptools on installation of the python formula (per https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md#setuptools-pip-etc), I tried using it to build sphinx-doc.

```
sudo apt-get uninstall python-setuptools
brew install sphinx-doc                                    // fails to build
brew install python
brew install sphinx-doc                                    // builds successfully
```
If this works for others, I think python should be added as a dependency of sphinx-doc on the linuxbrew repo.

**Comment by sjackman** [comment]
@MarcGodard Sorry for the delay in my response. I've just returned from a long vacation.

Thank you for the detailed bug report and excellent troubleshooting. Were you able to install `cmake`?

**Comment by sjackman** [comment]
I'm closing this issue. Please comment if you're still having difficulty installing `cmake`.
