### ISSUE TITLE
pam: Create formula for Linuxbrew

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/linuxbrew#946]
Homepage: http://www.linux-pam.org/

**Comment by sjackman** [comment]
rstudio-server: Depends on pam #819

**Comment by rwhogg** [comment]
I'm happy to take this one on, but it's not all that high priority for me right now. I'll increase priority on it if you want to use R Studio, but since the only other formula I'm aware of that uses it is CVS (not exactly the most important formula in the world these days) I think dealing with X11 is more important right now.

**Comment by sjackman** [comment]
Agreed. I use RStudio on Mac. On Linux I use only R command line.

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#131
