### ISSUE TITLE
glibc: Bottle not on Bintray: 404 Not Found

### ISSUE THREAD

**Issue by DoomHammer** [Linuxbrew/linuxbrew#952]
Running `brew install gcc --with-glibc` I got:

```
==> Installing gcc dependency: glibc
==> Downloading https://linuxbrew.bintray.com/bottles/glibc-2.19.x86_64_linux.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "glibc"
Download failed: https://linuxbrew.bintray.com/bottles/glibc-2.19.x86_64_linux.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

Env: Docker `linuxbrew/linuxbrew` `7c827ee662db`, Homebrew `f0e235a`

**Comment by sjackman** [comment]
Yep, that was me. I added the bottle stanza of the `glibc` formula, but then never uploaded the binary to Bintray, because I wanted to test it more, and then forgot to remove the bottle stanza from `glibc`. Note that `glibc` is not `cellar :any`, so this bug only affects installations of Linuxbrew to the prefix `/home/linuxbrew/.linuxbrew`. The quick fix is to remove the bottle stanza from `glibc`. I do want to bottle `glibc` particularly because it would speed up the builds on Travis CI, which uses Ubuntu 12 Precise.

**Comment by mulle-nat** [comment]
When I run something on "Travis-CI", I always have to compile glibc. There is no bottle.

```
==> Installing mulle-kybernetik/software/mulle-build dependency: glibc
sudo: must be setuid root
==> Downloading https://ftpmirror.gnu.org/glibc/glibc-2.19.tar.bz2
==> Downloading from http://gnu.mirror.constant.com/glibc/glibc-2.19.tar.bz2
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-
==> make
==> make install
```
This makes things very slow and also burdens travis. The same happens with openssl.

**Comment by maxim-belkin** [comment]
> Edit: Sorry I just noticed this is legacy-linuxbrew, possibly the wrong repository.

Yep

**Comment by sjackman** [comment]
The `glibc` bottle is not relocatable. You have to install Linuxbrew in `/home/linuxbrew/.linuxbrew` to use the bottle. I'm going to lock this issue. Feel free to open a new issue at https://github.com/Linuxbrew/brew
